import type { TournamentState } from '../types'

export const initialState: TournamentState = {
  tType: 'singles',
  bMethod: 'skill',
  tournamentName: 'Tournament',
  settings: {
    winScore: 11,
    winBy2: true,
    groupStageBestOf: 1,
    advanceCount: 2,
    quarterFinalsBestOf: 1,
    sfBestOf: 3,
    finalsBestOf: 5,
    thirdBestOf: 3,
    numGroups: 2,
    matchDuration: 20,
  },
  teams: [],
  groups: [],
  rrMatches: {},
  bracketMatches: [],
  bracketRounds: [],
  thirdPlaceMatch: null,
  courts: [],
  schedule: {},
  history: [],
  bracketSeedGroups: {},
  _tid: 1,
  _mid: 1,
  _cid: 1,
  wsStatus: 'offline',
  wsStatusText: '',
  role: 'viewer',
  tournamentId: null,
  presenceCount: 0,
  activePage: 'setup',
  curRRGroup: 0,
  confettiShown: false,
  toast: null,
  testingMode: false,
}
